var Jasteroids = Jasteroids || {};

Jasteroids.Settings = {
    EXPLODING_POLYGON_MAX_AGE: 14,
    EXPLODING_POLYGON_LINE_VELOCITY: 15,
    SPACE_SHIP_THRUST: 60,
    SPACE_SHIP_REVERSE_THRUST: 20,
    SPACE_SHIP_MORTAL_AGE: 20,
    SPACE_SHIP_MAX_SPEED: 140,
    SPACE_SHIP_SCALE: 25
};

